<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CustomersTableSeeder extends Seeder
{
    /**
     * Auto generated seeder file.
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('customers')->delete();
        
        \DB::table('customers')->insert(array (
            0 => 
            array (
                'id' => 2,
                'code' => 'R9-CSTMR-00001',
                'name' => 'Dressing Plant',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 23,
                'classification_id' => 8,
                'name_id' => 2,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 13:35:41',
                'updated_at' => '2024-07-30 13:35:41',
            ),
            1 => 
            array (
                'id' => 3,
                'code' => 'R9-CSTMR-00002',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 25,
                'classification_id' => 8,
                'name_id' => 3,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 13:48:15',
                'updated_at' => '2024-07-30 13:48:15',
            ),
            2 => 
            array (
                'id' => 4,
                'code' => 'R9-CSTMR-00003',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 16,
                'classification_id' => 8,
                'name_id' => 6,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 13:57:10',
                'updated_at' => '2024-07-30 13:57:10',
            ),
            3 => 
            array (
                'id' => 5,
                'code' => 'R9-CSTMR-00004',
                'name' => 'Isabela City',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 22,
                'classification_id' => 8,
                'name_id' => 7,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 14:02:23',
                'updated_at' => '2024-07-30 14:02:23',
            ),
            4 => 
            array (
                'id' => 6,
                'code' => 'R9-CSTMR-00005',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 22,
                'classification_id' => 8,
                'name_id' => 8,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 14:05:08',
                'updated_at' => '2024-07-30 14:05:08',
            ),
            5 => 
            array (
                'id' => 7,
                'code' => 'R9-CSTMR-00006',
                'name' => 'Microbiological Laboratory',
                'is_main' => 0,
                'is_internal' => 1,
                'is_active' => 1,
                'industry_id' => 22,
                'classification_id' => 8,
                'name_id' => 9,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 14:08:45',
                'updated_at' => '2024-07-30 14:08:45',
            ),
            6 => 
            array (
                'id' => 8,
                'code' => 'R9-CSTMR-00007',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 95,
                'classification_id' => 8,
                'name_id' => 10,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 14:12:39',
                'updated_at' => '2024-07-30 14:12:39',
            ),
            7 => 
            array (
                'id' => 9,
                'code' => 'R9-CSTMR-00008',
                'name' => 'Metrology Laboratory',
                'is_main' => 0,
                'is_internal' => 1,
                'is_active' => 1,
                'industry_id' => 22,
                'classification_id' => 8,
                'name_id' => 9,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 14:14:49',
                'updated_at' => '2024-07-30 14:14:49',
            ),
            8 => 
            array (
                'id' => 10,
                'code' => 'R9-CSTMR-00009',
                'name' => 'Chemical Laboratory',
                'is_main' => 0,
                'is_internal' => 1,
                'is_active' => 1,
                'industry_id' => 22,
                'classification_id' => 8,
                'name_id' => 9,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 14:16:09',
                'updated_at' => '2024-07-30 14:16:09',
            ),
            9 => 
            array (
                'id' => 11,
                'code' => 'R9-CSTMR-00010',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 31,
                'classification_id' => 8,
                'name_id' => 11,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 14:24:37',
                'updated_at' => '2024-07-30 14:24:37',
            ),
            10 => 
            array (
                'id' => 12,
                'code' => 'R9-CSTMR-00011',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 31,
                'classification_id' => 8,
                'name_id' => 12,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 14:27:56',
                'updated_at' => '2024-07-30 14:27:56',
            ),
            11 => 
            array (
                'id' => 13,
                'code' => 'R9-CSTMR-00012',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 95,
                'classification_id' => 8,
                'name_id' => 13,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 14:31:01',
                'updated_at' => '2024-07-30 14:31:01',
            ),
            12 => 
            array (
                'id' => 14,
                'code' => 'R9-CSTMR-00013',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 54,
                'classification_id' => 8,
                'name_id' => 14,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 14:55:55',
                'updated_at' => '2024-07-30 14:55:55',
            ),
            13 => 
            array (
                'id' => 15,
                'code' => 'R9-CSTMR-00014',
                'name' => 'R.T Lim',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 22,
                'classification_id' => 8,
                'name_id' => 15,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 14:58:27',
                'updated_at' => '2024-07-30 14:58:27',
            ),
            14 => 
            array (
                'id' => 16,
                'code' => 'R9-CSTMR-00015',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 25,
                'classification_id' => 8,
                'name_id' => 16,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:00:14',
                'updated_at' => '2024-07-30 15:00:14',
            ),
            15 => 
            array (
                'id' => 17,
                'code' => 'R9-CSTMR-00016',
                'name' => 'Western Mindanao Regional Office IX',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 22,
                'classification_id' => 8,
                'name_id' => 17,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:02:14',
                'updated_at' => '2024-07-30 15:02:14',
            ),
            16 => 
            array (
                'id' => 18,
                'code' => 'R9-CSTMR-00017',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 95,
                'classification_id' => 8,
                'name_id' => 18,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:03:40',
                'updated_at' => '2024-07-30 15:03:40',
            ),
            17 => 
            array (
                'id' => 19,
                'code' => 'R9-CSTMR-00018',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 25,
                'classification_id' => 8,
                'name_id' => 19,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:05:39',
                'updated_at' => '2024-07-30 15:05:39',
            ),
            18 => 
            array (
                'id' => 20,
                'code' => 'R9-CSTMR-00019',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 8,
                'name_id' => 20,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:08:30',
                'updated_at' => '2024-07-30 15:08:30',
            ),
            19 => 
            array (
                'id' => 21,
                'code' => 'R9-CSTMR-00020',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 107,
                'classification_id' => 9,
                'name_id' => 21,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:11:24',
                'updated_at' => '2024-07-30 15:11:24',
            ),
            20 => 
            array (
                'id' => 22,
                'code' => 'R9-CSTMR-00021',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 25,
                'classification_id' => 8,
                'name_id' => 22,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:13:55',
                'updated_at' => '2024-07-30 15:13:55',
            ),
            21 => 
            array (
                'id' => 23,
                'code' => 'R9-CSTMR-00022',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 25,
                'classification_id' => 8,
                'name_id' => 23,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:16:22',
                'updated_at' => '2024-07-30 15:16:22',
            ),
            22 => 
            array (
                'id' => 24,
                'code' => 'R9-CSTMR-00023',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 25,
                'classification_id' => 8,
                'name_id' => 24,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:17:55',
                'updated_at' => '2024-07-30 15:17:55',
            ),
            23 => 
            array (
                'id' => 25,
                'code' => 'R9-CSTMR-00024',
                'name' => 'Rizal Avenue',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 41,
                'classification_id' => 8,
                'name_id' => 25,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:20:39',
                'updated_at' => '2024-07-30 15:20:39',
            ),
            24 => 
            array (
                'id' => 26,
                'code' => 'R9-CSTMR-00025',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 25,
                'classification_id' => 8,
                'name_id' => 26,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:23:05',
                'updated_at' => '2024-07-30 15:23:05',
            ),
            25 => 
            array (
                'id' => 27,
                'code' => 'R9-CSTMR-00026',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 12,
                'classification_id' => 8,
                'name_id' => 27,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:25:53',
                'updated_at' => '2024-07-30 15:25:53',
            ),
            26 => 
            array (
                'id' => 28,
                'code' => 'R9-CSTMR-00027',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 67,
                'classification_id' => 8,
                'name_id' => 28,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:28:12',
                'updated_at' => '2024-07-30 15:28:12',
            ),
            27 => 
            array (
                'id' => 29,
                'code' => 'R9-CSTMR-00028',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 25,
                'classification_id' => 8,
                'name_id' => 29,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:30:29',
                'updated_at' => '2024-07-30 15:30:29',
            ),
            28 => 
            array (
                'id' => 30,
                'code' => 'R9-CSTMR-00029',
                'name' => 'Titay Plant',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 8,
                'name_id' => 30,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:32:52',
                'updated_at' => '2024-07-30 15:32:52',
            ),
            29 => 
            array (
                'id' => 31,
                'code' => 'R9-CSTMR-00030',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 8,
                'name_id' => 31,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:34:51',
                'updated_at' => '2024-07-30 15:34:51',
            ),
            30 => 
            array (
                'id' => 32,
                'code' => 'R9-CSTMR-00031',
                'name' => 'Region IX',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 22,
                'classification_id' => 8,
                'name_id' => 32,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:40:12',
                'updated_at' => '2024-07-30 15:40:12',
            ),
            31 => 
            array (
                'id' => 33,
                'code' => 'R9-CSTMR-00032',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 8,
                'name_id' => 33,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:42:45',
                'updated_at' => '2024-07-30 15:42:45',
            ),
            32 => 
            array (
                'id' => 34,
                'code' => 'R9-CSTMR-00033',
                'name' => 'Mindanao Livestock Production Center',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 23,
                'classification_id' => 8,
                'name_id' => 34,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:46:18',
                'updated_at' => '2024-07-30 15:46:18',
            ),
            33 => 
            array (
                'id' => 35,
                'code' => 'R9-CSTMR-00034',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 56,
                'classification_id' => 8,
                'name_id' => 35,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:47:49',
                'updated_at' => '2024-07-30 15:47:49',
            ),
            34 => 
            array (
                'id' => 36,
                'code' => 'R9-CSTMR-00035',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 96,
                'classification_id' => 8,
                'name_id' => 36,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:49:30',
                'updated_at' => '2024-07-30 15:49:30',
            ),
            35 => 
            array (
                'id' => 37,
                'code' => 'R9-CSTMR-00036',
                'name' => 'Greenwhich Camins',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 72,
                'classification_id' => 8,
                'name_id' => 37,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:52:41',
                'updated_at' => '2024-07-30 15:52:41',
            ),
            36 => 
            array (
                'id' => 38,
                'code' => 'R9-CSTMR-00037',
                'name' => 'Greenwich Ipil',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 72,
                'classification_id' => 8,
                'name_id' => 38,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:55:53',
                'updated_at' => '2024-07-30 15:55:53',
            ),
            37 => 
            array (
                'id' => 39,
                'code' => 'R9-CSTMR-00038',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 8,
                'name_id' => 39,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:59:51',
                'updated_at' => '2024-07-30 15:59:51',
            ),
            38 => 
            array (
                'id' => 40,
                'code' => 'R9-CSTMR-00039',
                'name' => 'Western Mindanao',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 8,
                'name_id' => 30,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:06:20',
                'updated_at' => '2024-07-30 16:06:20',
            ),
            39 => 
            array (
                'id' => 41,
                'code' => 'R9-CSTMR-00040',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 12,
                'classification_id' => 8,
                'name_id' => 40,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:11:41',
                'updated_at' => '2024-07-30 16:11:41',
            ),
            40 => 
            array (
                'id' => 42,
                'code' => 'R9-CSTMR-00041',
                'name' => 'Tetuan',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 95,
                'classification_id' => 8,
                'name_id' => 41,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:13:23',
                'updated_at' => '2024-07-30 16:13:23',
            ),
            41 => 
            array (
                'id' => 43,
                'code' => 'R9-CSTMR-00042',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 60,
                'classification_id' => 8,
                'name_id' => 42,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:15:08',
                'updated_at' => '2024-07-30 16:15:08',
            ),
            42 => 
            array (
                'id' => 44,
                'code' => 'R9-CSTMR-00043',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 56,
                'classification_id' => 8,
                'name_id' => 43,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:16:59',
                'updated_at' => '2024-07-30 16:16:59',
            ),
            43 => 
            array (
                'id' => 45,
                'code' => 'R9-CSTMR-00044',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 42,
                'classification_id' => 8,
                'name_id' => 44,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:20:12',
                'updated_at' => '2024-07-30 16:20:12',
            ),
            44 => 
            array (
                'id' => 46,
                'code' => 'R9-CSTMR-00045',
                'name' => 'Culianan',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 95,
                'classification_id' => 9,
                'name_id' => 41,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:21:41',
                'updated_at' => '2024-07-30 16:21:41',
            ),
            45 => 
            array (
                'id' => 47,
                'code' => 'R9-CSTMR-00046',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 71,
                'classification_id' => 8,
                'name_id' => 45,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:23:56',
                'updated_at' => '2024-07-30 16:23:56',
            ),
            46 => 
            array (
                'id' => 48,
                'code' => 'R9-CSTMR-00047',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 72,
                'classification_id' => 8,
                'name_id' => 46,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:25:43',
                'updated_at' => '2024-07-30 16:25:43',
            ),
            47 => 
            array (
                'id' => 49,
                'code' => 'R9-CSTMR-00048',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 25,
                'classification_id' => 8,
                'name_id' => 47,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:27:32',
                'updated_at' => '2024-07-30 16:27:32',
            ),
            48 => 
            array (
                'id' => 50,
                'code' => 'R9-CSTMR-00049',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 84,
                'classification_id' => 8,
                'name_id' => 48,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:29:49',
                'updated_at' => '2024-07-30 16:29:49',
            ),
            49 => 
            array (
                'id' => 51,
                'code' => 'R9-CSTMR-00050',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 72,
                'classification_id' => 8,
                'name_id' => 49,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:34:00',
                'updated_at' => '2024-07-30 16:34:00',
            ),
            50 => 
            array (
                'id' => 52,
                'code' => 'R9-CSTMR-00051',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 95,
                'classification_id' => 8,
                'name_id' => 50,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:35:34',
                'updated_at' => '2024-07-30 16:35:34',
            ),
            51 => 
            array (
                'id' => 53,
                'code' => 'R9-CSTMR-00052',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 103,
                'classification_id' => 8,
                'name_id' => 51,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:36:48',
                'updated_at' => '2024-07-30 16:36:48',
            ),
            52 => 
            array (
                'id' => 54,
                'code' => 'R9-CSTMR-00053',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 104,
                'classification_id' => 8,
                'name_id' => 52,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:39:02',
                'updated_at' => '2024-07-30 16:39:02',
            ),
            53 => 
            array (
                'id' => 55,
                'code' => 'R9-CSTMR-00054',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 71,
                'classification_id' => 8,
                'name_id' => 53,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:40:28',
                'updated_at' => '2024-07-30 16:40:28',
            ),
            54 => 
            array (
                'id' => 56,
                'code' => 'R9-CSTMR-00055',
                'name' => 'Jollibee Basilan',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 72,
                'classification_id' => 8,
                'name_id' => 54,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:41:53',
                'updated_at' => '2024-07-30 16:41:53',
            ),
            55 => 
            array (
                'id' => 57,
                'code' => 'R9-CSTMR-00056',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 104,
                'classification_id' => 8,
                'name_id' => 55,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:43:08',
                'updated_at' => '2024-07-30 16:43:08',
            ),
            56 => 
            array (
                'id' => 58,
                'code' => 'R9-CSTMR-00057',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 56,
                'classification_id' => 8,
                'name_id' => 56,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:44:17',
                'updated_at' => '2024-07-30 16:44:17',
            ),
            57 => 
            array (
                'id' => 59,
                'code' => 'R9-CSTMR-00058',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 25,
                'classification_id' => 8,
                'name_id' => 57,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:47:53',
                'updated_at' => '2024-07-30 16:47:53',
            ),
            58 => 
            array (
                'id' => 60,
                'code' => 'R9-CSTMR-00059',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 56,
                'classification_id' => 8,
                'name_id' => 58,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:48:58',
                'updated_at' => '2024-07-30 16:48:58',
            ),
            59 => 
            array (
                'id' => 61,
                'code' => 'R9-CSTMR-00060',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 25,
                'classification_id' => 8,
                'name_id' => 59,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:50:15',
                'updated_at' => '2024-07-30 16:50:15',
            ),
            60 => 
            array (
                'id' => 62,
                'code' => 'R9-CSTMR-00061',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 72,
                'classification_id' => 8,
                'name_id' => 60,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:54:24',
                'updated_at' => '2024-07-30 16:54:24',
            ),
            61 => 
            array (
                'id' => 63,
                'code' => 'R9-CSTMR-00062',
                'name' => 'Zamboanga Station',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 68,
                'classification_id' => 8,
                'name_id' => 61,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:56:37',
                'updated_at' => '2024-07-30 16:56:37',
            ),
            62 => 
            array (
                'id' => 64,
                'code' => 'R9-CSTMR-00063',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 8,
                'name_id' => 62,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:58:37',
                'updated_at' => '2024-07-30 16:58:37',
            ),
            63 => 
            array (
                'id' => 65,
                'code' => 'R9-CSTMR-00064',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 25,
                'classification_id' => 8,
                'name_id' => 63,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:59:47',
                'updated_at' => '2024-07-30 16:59:47',
            ),
            64 => 
            array (
                'id' => 66,
                'code' => 'R9-CSTMR-00065',
                'name' => 'Dipolog Branch',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 8,
                'name_id' => 64,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 17:01:11',
                'updated_at' => '2024-07-30 17:01:11',
            ),
            65 => 
            array (
                'id' => 67,
                'code' => 'R9-CSTMR-00066',
                'name' => 'Piñan Branch',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 8,
                'name_id' => 64,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 17:02:26',
                'updated_at' => '2024-07-30 17:02:26',
            ),
            66 => 
            array (
                'id' => 68,
                'code' => 'R9-CSTMR-00067',
                'name' => 'Health Service Division',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 22,
                'classification_id' => 8,
                'name_id' => 65,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 18:24:31',
                'updated_at' => '2024-07-30 18:24:31',
            ),
            67 => 
            array (
                'id' => 69,
                'code' => 'R9-CSTMR-00068',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 25,
                'classification_id' => 8,
                'name_id' => 66,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 18:28:33',
                'updated_at' => '2024-07-30 18:28:33',
            ),
            68 => 
            array (
                'id' => 70,
                'code' => 'R9-CSTMR-00069',
                'name' => 'Zamboanga City',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 8,
                'name_id' => 67,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 18:31:00',
                'updated_at' => '2024-07-30 18:31:00',
            ),
            69 => 
            array (
                'id' => 71,
                'code' => 'R9-CSTMR-00070',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 95,
                'classification_id' => 8,
                'name_id' => 68,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 18:33:34',
                'updated_at' => '2024-07-30 18:33:34',
            ),
            70 => 
            array (
                'id' => 72,
                'code' => 'R9-CSTMR-00071',
                'name' => 'Molave Municipal Jail',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 22,
                'classification_id' => 8,
                'name_id' => 65,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 18:35:56',
                'updated_at' => '2024-07-30 18:35:56',
            ),
            71 => 
            array (
                'id' => 73,
                'code' => 'R9-CSTMR-00072',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 72,
                'classification_id' => 8,
                'name_id' => 69,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 18:41:59',
                'updated_at' => '2024-07-30 18:41:59',
            ),
            72 => 
            array (
                'id' => 74,
                'code' => 'R9-CSTMR-00073',
                'name' => 'Tetuan Branch',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 72,
                'classification_id' => 8,
                'name_id' => 70,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 18:43:52',
                'updated_at' => '2024-07-30 18:43:52',
            ),
            73 => 
            array (
                'id' => 75,
                'code' => 'R9-CSTMR-00074',
                'name' => 'Katipunan Branch',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 8,
                'name_id' => 71,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 18:45:15',
                'updated_at' => '2024-07-30 18:45:15',
            ),
            74 => 
            array (
                'id' => 76,
                'code' => 'R9-CSTMR-00075',
                'name' => 'Sindangan Branch',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 8,
                'name_id' => 71,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 18:46:25',
                'updated_at' => '2024-07-30 18:46:25',
            ),
            75 => 
            array (
                'id' => 77,
                'code' => 'R9-CSTMR-00076',
                'name' => 'Roxas Branch',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 8,
                'name_id' => 71,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 18:48:40',
                'updated_at' => '2024-07-30 18:48:40',
            ),
            76 => 
            array (
                'id' => 78,
                'code' => 'R9-CSTMR-00077',
            'name' => 'Zamboanga City Jail (Female Dormitory)',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 22,
                'classification_id' => 8,
                'name_id' => 65,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 18:52:08',
                'updated_at' => '2024-07-30 18:52:08',
            ),
            77 => 
            array (
                'id' => 79,
                'code' => 'R9-CSTMR-00078',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 29,
                'classification_id' => 8,
                'name_id' => 72,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 18:55:17',
                'updated_at' => '2024-07-30 18:55:17',
            ),
            78 => 
            array (
                'id' => 80,
                'code' => 'R9-CSTMR-00079',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 95,
                'classification_id' => 8,
                'name_id' => 73,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 18:57:43',
                'updated_at' => '2024-07-30 18:57:43',
            ),
            79 => 
            array (
                'id' => 81,
                'code' => 'R9-CSTMR-00080',
                'name' => 'Gateway Branch',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 95,
                'classification_id' => 8,
                'name_id' => 74,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 18:59:21',
                'updated_at' => '2024-07-30 18:59:21',
            ),
            80 => 
            array (
                'id' => 82,
                'code' => 'R9-CSTMR-00081',
                'name' => 'Ayala Branch',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 95,
                'classification_id' => 8,
                'name_id' => 74,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 19:00:29',
                'updated_at' => '2024-07-30 19:00:29',
            ),
            81 => 
            array (
                'id' => 83,
                'code' => 'R9-CSTMR-00082',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 107,
                'classification_id' => 9,
                'name_id' => 75,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 19:02:24',
                'updated_at' => '2024-07-30 19:02:24',
            ),
            82 => 
            array (
                'id' => 84,
                'code' => 'R9-CSTMR-00083',
                'name' => 'Zamboanga',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 22,
                'classification_id' => 8,
                'name_id' => 76,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 19:03:58',
                'updated_at' => '2024-07-30 19:03:58',
            ),
            83 => 
            array (
                'id' => 85,
                'code' => 'R9-CSTMR-00084',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 95,
                'classification_id' => 8,
                'name_id' => 77,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 19:06:29',
                'updated_at' => '2024-07-30 19:06:29',
            ),
            84 => 
            array (
                'id' => 86,
                'code' => 'R9-CSTMR-00085',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 25,
                'classification_id' => 8,
                'name_id' => 78,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 19:07:24',
                'updated_at' => '2024-07-30 19:07:24',
            ),
            85 => 
            array (
                'id' => 87,
                'code' => 'R9-CSTMR-00086',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 31,
                'classification_id' => 8,
                'name_id' => 79,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 19:08:16',
                'updated_at' => '2024-07-30 19:08:16',
            ),
            86 => 
            array (
                'id' => 88,
                'code' => 'R9-CSTMR-00087',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 104,
                'classification_id' => 8,
                'name_id' => 80,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 19:09:11',
                'updated_at' => '2024-07-30 19:09:11',
            ),
            87 => 
            array (
                'id' => 89,
                'code' => 'R9-CSTMR-00088',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 8,
                'name_id' => 81,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 19:11:41',
                'updated_at' => '2024-07-30 19:11:41',
            ),
            88 => 
            array (
                'id' => 90,
                'code' => 'R9-CSTMR-00089',
                'name' => 'Tandubas',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 22,
                'classification_id' => 8,
                'name_id' => 15,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 19:13:25',
                'updated_at' => '2024-07-30 19:13:25',
            ),
            89 => 
            array (
                'id' => 91,
                'code' => 'R9-CSTMR-00090',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 62,
                'classification_id' => 8,
                'name_id' => 82,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 19:14:41',
                'updated_at' => '2024-07-30 19:14:41',
            ),
            90 => 
            array (
                'id' => 92,
                'code' => 'R9-CSTMR-00091',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 104,
                'classification_id' => 8,
                'name_id' => 83,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 19:16:01',
                'updated_at' => '2024-07-30 19:16:01',
            ),
            91 => 
            array (
                'id' => 93,
                'code' => 'R9-CSTMR-00092',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 72,
                'classification_id' => 8,
                'name_id' => 84,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-07 08:12:24',
                'updated_at' => '2024-08-07 08:12:24',
            ),
            92 => 
            array (
                'id' => 94,
                'code' => 'R9-CSTMR-00093',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 8,
                'name_id' => 85,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-07 08:15:37',
                'updated_at' => '2024-08-07 08:15:37',
            ),
            93 => 
            array (
                'id' => 95,
                'code' => 'R9-CSTMR-00094',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 56,
                'classification_id' => 8,
                'name_id' => 86,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-07 08:17:35',
                'updated_at' => '2024-08-07 08:17:35',
            ),
            94 => 
            array (
                'id' => 96,
                'code' => 'R9-CSTMR-00095',
                'name' => 'Zamboanga Sibugay',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 22,
                'classification_id' => 8,
                'name_id' => 87,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-07 08:19:12',
                'updated_at' => '2024-08-07 08:19:12',
            ),
            95 => 
            array (
                'id' => 97,
                'code' => 'R9-CSTMR-00096',
                'name' => 'Sinunuc',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 95,
                'classification_id' => 8,
                'name_id' => 88,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-07 08:21:15',
                'updated_at' => '2024-08-07 08:21:15',
            ),
            96 => 
            array (
                'id' => 98,
                'code' => 'R9-CSTMR-00097',
                'name' => 'Buug',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 95,
                'classification_id' => 8,
                'name_id' => 88,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-07 08:22:37',
                'updated_at' => '2024-08-07 08:22:37',
            ),
            97 => 
            array (
                'id' => 99,
                'code' => 'R9-CSTMR-00098',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 95,
                'classification_id' => 8,
                'name_id' => 89,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-07 08:25:53',
                'updated_at' => '2024-08-07 08:25:53',
            ),
            98 => 
            array (
                'id' => 100,
                'code' => 'R9-CSTMR-00099',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 8,
                'name_id' => 90,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-07 08:30:38',
                'updated_at' => '2024-08-07 08:30:38',
            ),
            99 => 
            array (
                'id' => 101,
                'code' => 'R9-CSTMR-00100',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 95,
                'classification_id' => 8,
                'name_id' => 91,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-07 08:32:51',
                'updated_at' => '2024-08-07 08:32:51',
            ),
            100 => 
            array (
                'id' => 102,
                'code' => 'R9-CSTMR-00101',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 95,
                'classification_id' => 8,
                'name_id' => 92,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-07 08:35:20',
                'updated_at' => '2024-08-07 08:35:20',
            ),
            101 => 
            array (
                'id' => 103,
                'code' => 'R9-CSTMR-00102',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 107,
                'classification_id' => 9,
                'name_id' => 93,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-07 08:37:53',
                'updated_at' => '2024-08-07 08:37:53',
            ),
            102 => 
            array (
                'id' => 104,
                'code' => 'R9-CSTMR-00103',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 72,
                'classification_id' => 8,
                'name_id' => 94,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-14 09:09:26',
                'updated_at' => '2024-08-14 09:09:26',
            ),
            103 => 
            array (
                'id' => 105,
                'code' => 'R9-CSTMR-00104',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 29,
                'classification_id' => 8,
                'name_id' => 95,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-14 09:11:26',
                'updated_at' => '2024-08-14 09:11:26',
            ),
            104 => 
            array (
                'id' => 106,
                'code' => 'R9-CSTMR-00105',
                'name' => 'Doña Isabel Cortez Climaco',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 22,
                'classification_id' => 8,
                'name_id' => 41,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-14 09:15:41',
                'updated_at' => '2024-08-14 09:15:41',
            ),
            105 => 
            array (
                'id' => 107,
                'code' => 'R9-CSTMR-00106',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 95,
                'classification_id' => 8,
                'name_id' => 96,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-14 09:18:10',
                'updated_at' => '2024-08-14 09:18:10',
            ),
            106 => 
            array (
                'id' => 108,
                'code' => 'R9-CSTMR-00107',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 87,
                'classification_id' => 8,
                'name_id' => 97,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-14 09:19:57',
                'updated_at' => '2024-08-14 09:19:57',
            ),
            107 => 
            array (
                'id' => 109,
                'code' => 'R9-CSTMR-00108',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 8,
                'name_id' => 98,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-14 09:21:14',
                'updated_at' => '2024-08-14 09:21:14',
            ),
            108 => 
            array (
                'id' => 110,
                'code' => 'R9-CSTMR-00109',
                'name' => 'Santa Barbara',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 95,
                'classification_id' => 8,
                'name_id' => 99,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-14 09:26:16',
                'updated_at' => '2024-08-14 09:26:16',
            ),
            109 => 
            array (
                'id' => 111,
                'code' => 'R9-CSTMR-00110',
                'name' => 'VIII',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 22,
                'classification_id' => 8,
                'name_id' => 100,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-14 09:30:14',
                'updated_at' => '2024-08-14 09:30:14',
            ),
            110 => 
            array (
                'id' => 112,
                'code' => 'R9-CSTMR-00111',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 60,
                'classification_id' => 8,
                'name_id' => 101,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-14 09:32:56',
                'updated_at' => '2024-08-14 09:32:56',
            ),
            111 => 
            array (
                'id' => 113,
                'code' => 'R9-CSTMR-00112',
                'name' => 'San Jose',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 95,
                'classification_id' => 8,
                'name_id' => 99,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-14 09:34:13',
                'updated_at' => '2024-08-14 09:34:13',
            ),
            112 => 
            array (
                'id' => 114,
                'code' => 'R9-CSTMR-00113',
                'name' => 'Dapitan',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 22,
                'classification_id' => 8,
                'name_id' => 15,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-14 09:36:22',
                'updated_at' => '2024-08-14 09:36:22',
            ),
            113 => 
            array (
                'id' => 115,
                'code' => 'R9-CSTMR-00114',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 95,
                'classification_id' => 8,
                'name_id' => 102,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-14 09:38:12',
                'updated_at' => '2024-08-14 09:38:12',
            ),
            114 => 
            array (
                'id' => 116,
                'code' => 'R9-CSTMR-00115',
                'name' => 'Labuan',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 8,
                'name_id' => 103,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-14 09:39:49',
                'updated_at' => '2024-08-14 09:39:49',
            ),
            115 => 
            array (
                'id' => 117,
                'code' => 'R9-CSTMR-00116',
                'name' => 'Zamboanga City',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 67,
                'classification_id' => 8,
                'name_id' => 104,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-14 09:45:13',
                'updated_at' => '2024-08-14 09:45:13',
            ),
            116 => 
            array (
                'id' => 118,
                'code' => 'R9-CSTMR-00117',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 95,
                'classification_id' => 8,
                'name_id' => 105,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-14 09:50:29',
                'updated_at' => '2024-08-14 09:50:29',
            ),
            117 => 
            array (
                'id' => 119,
                'code' => 'R9-CSTMR-00118',
                'name' => 'Camino Nuevo Branch',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 95,
                'classification_id' => 8,
                'name_id' => 70,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-16 08:18:29',
                'updated_at' => '2024-08-16 08:18:29',
            ),
            118 => 
            array (
                'id' => 120,
                'code' => 'R9-CSTMR-00119',
                'name' => 'Veterans Branch',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 95,
                'classification_id' => 8,
                'name_id' => 74,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-16 08:23:15',
                'updated_at' => '2024-08-16 08:23:15',
            ),
            119 => 
            array (
                'id' => 121,
                'code' => 'R9-CSTMR-00120',
                'name' => 'Putik Branch',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 95,
                'classification_id' => 8,
                'name_id' => 74,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-16 08:24:44',
                'updated_at' => '2024-08-16 08:24:44',
            ),
            120 => 
            array (
                'id' => 122,
                'code' => 'R9-CSTMR-00121',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 31,
                'classification_id' => 8,
                'name_id' => 106,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-16 08:26:57',
                'updated_at' => '2024-08-16 08:26:57',
            ),
            121 => 
            array (
                'id' => 123,
                'code' => 'R9-CSTMR-00122',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 8,
                'name_id' => 107,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-16 08:28:10',
                'updated_at' => '2024-08-16 08:28:10',
            ),
            122 => 
            array (
                'id' => 124,
                'code' => 'R9-CSTMR-00123',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 16,
                'classification_id' => 8,
                'name_id' => 108,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-16 16:54:21',
                'updated_at' => '2024-08-16 16:54:21',
            ),
            123 => 
            array (
                'id' => 125,
                'code' => 'R9-CSTMR-00124',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 56,
                'classification_id' => 8,
                'name_id' => 109,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-16 17:00:01',
                'updated_at' => '2024-08-16 17:00:01',
            ),
            124 => 
            array (
                'id' => 126,
                'code' => 'R9-CSTMR-00125',
                'name' => 'RDEC',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 16,
                'classification_id' => 8,
                'name_id' => 110,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-16 17:02:46',
                'updated_at' => '2024-08-16 17:02:46',
            ),
            125 => 
            array (
                'id' => 127,
                'code' => 'R9-CSTMR-00126',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 60,
                'classification_id' => 8,
                'name_id' => 111,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-19 14:36:39',
                'updated_at' => '2024-08-19 14:36:39',
            ),
            126 => 
            array (
                'id' => 128,
                'code' => 'R9-CSTMR-00127',
                'name' => 'Guiwan',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 8,
                'name_id' => 103,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-19 14:37:58',
                'updated_at' => '2024-08-19 14:37:58',
            ),
            127 => 
            array (
                'id' => 129,
                'code' => 'R9-CSTMR-00128',
                'name' => 'Zamboanga Plant',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 32,
                'classification_id' => 8,
                'name_id' => 112,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-19 14:40:12',
                'updated_at' => '2024-08-19 14:40:12',
            ),
            128 => 
            array (
                'id' => 130,
                'code' => 'R9-CSTMR-00129',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 60,
                'classification_id' => 8,
                'name_id' => 113,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-19 14:41:21',
                'updated_at' => '2024-08-19 14:41:21',
            ),
            129 => 
            array (
                'id' => 131,
                'code' => 'R9-CSTMR-00130',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 104,
                'classification_id' => 8,
                'name_id' => 114,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-19 15:11:30',
                'updated_at' => '2024-08-19 15:11:30',
            ),
            130 => 
            array (
                'id' => 132,
                'code' => 'R9-CSTMR-00131',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 56,
                'classification_id' => 8,
                'name_id' => 115,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-21 08:20:59',
                'updated_at' => '2024-08-21 08:20:59',
            ),
            131 => 
            array (
                'id' => 133,
                'code' => 'R9-CSTMR-00132',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 8,
                'name_id' => 116,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-21 08:22:49',
                'updated_at' => '2024-08-21 08:22:49',
            ),
            132 => 
            array (
                'id' => 134,
                'code' => 'R9-CSTMR-00133',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 107,
                'classification_id' => 9,
                'name_id' => 117,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-21 08:24:02',
                'updated_at' => '2024-08-21 08:24:02',
            ),
            133 => 
            array (
                'id' => 135,
                'code' => 'R9-CSTMR-00134',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 56,
                'classification_id' => 8,
                'name_id' => 118,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-21 08:26:22',
                'updated_at' => '2024-08-21 08:26:22',
            ),
            134 => 
            array (
                'id' => 136,
                'code' => 'R9-CSTMR-00135',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 72,
                'classification_id' => 8,
                'name_id' => 119,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-21 10:26:28',
                'updated_at' => '2024-08-21 10:26:28',
            ),
            135 => 
            array (
                'id' => 137,
                'code' => 'R9-CSTMR-00136',
                'name' => 'Larayan Branch',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 8,
                'name_id' => 120,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-28 16:43:51',
                'updated_at' => '2024-08-28 16:43:51',
            ),
            136 => 
            array (
                'id' => 138,
                'code' => 'R9-CSTMR-00137',
                'name' => 'KCC',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 31,
                'classification_id' => 8,
                'name_id' => 121,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-28 17:00:50',
                'updated_at' => '2024-08-28 17:00:50',
            ),
            137 => 
            array (
                'id' => 139,
                'code' => 'R9-CSTMR-00138',
                'name' => 'Purok Bougainvilla Branch',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 8,
                'name_id' => 122,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-28 17:06:00',
                'updated_at' => '2024-08-28 17:06:00',
            ),
            138 => 
            array (
                'id' => 140,
                'code' => 'R9-CSTMR-00139',
                'name' => 'Purok Airways Branch',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 8,
                'name_id' => 122,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-28 17:06:57',
                'updated_at' => '2024-08-28 17:06:57',
            ),
            139 => 
            array (
                'id' => 141,
                'code' => 'R9-CSTMR-00140',
                'name' => 'Imelda',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 22,
                'classification_id' => 8,
                'name_id' => 15,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-29 18:50:46',
                'updated_at' => '2024-08-29 18:50:46',
            ),
            140 => 
            array (
                'id' => 142,
                'code' => 'R9-CSTMR-00141',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 69,
                'classification_id' => 8,
                'name_id' => 123,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-29 18:54:42',
                'updated_at' => '2024-08-29 18:54:42',
            ),
            141 => 
            array (
                'id' => 143,
                'code' => 'R9-CSTMR-00142',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 104,
                'classification_id' => 8,
                'name_id' => 124,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-29 18:56:39',
                'updated_at' => '2024-08-29 18:56:39',
            ),
            142 => 
            array (
                'id' => 144,
                'code' => 'R9-CSTMR-00143',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 72,
                'classification_id' => 8,
                'name_id' => 125,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-29 18:58:11',
                'updated_at' => '2024-08-29 18:58:11',
            ),
            143 => 
            array (
                'id' => 145,
                'code' => 'R9-CSTMR-00144',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 8,
                'name_id' => 126,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-29 18:59:08',
                'updated_at' => '2024-08-29 18:59:08',
            ),
            144 => 
            array (
                'id' => 146,
                'code' => 'R9-CSTMR-00145',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 23,
                'classification_id' => 8,
                'name_id' => 127,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-29 19:01:52',
                'updated_at' => '2024-08-29 19:01:52',
            ),
            145 => 
            array (
                'id' => 147,
                'code' => 'R9-CSTMR-00146',
                'name' => 'Dumalinao',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 22,
                'classification_id' => 8,
                'name_id' => 15,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-29 19:03:26',
                'updated_at' => '2024-08-29 19:03:26',
            ),
            146 => 
            array (
                'id' => 148,
                'code' => 'R9-CSTMR-00147',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 25,
                'classification_id' => 8,
                'name_id' => 128,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-29 19:05:43',
                'updated_at' => '2024-08-29 19:05:43',
            ),
            147 => 
            array (
                'id' => 149,
                'code' => 'R9-CSTMR-00148',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 16,
                'classification_id' => 8,
                'name_id' => 129,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-29 19:06:54',
                'updated_at' => '2024-08-29 19:06:54',
            ),
            148 => 
            array (
                'id' => 150,
                'code' => 'R9-CSTMR-00149',
                'name' => 'Talisayan',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 25,
                'classification_id' => 8,
                'name_id' => 130,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-29 19:08:45',
                'updated_at' => '2024-08-29 19:08:45',
            ),
            149 => 
            array (
                'id' => 151,
                'code' => 'R9-CSTMR-00150',
                'name' => 'Kabasalan',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 22,
                'classification_id' => 8,
                'name_id' => 15,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-29 19:10:16',
                'updated_at' => '2024-08-29 19:10:16',
            ),
            150 => 
            array (
                'id' => 152,
                'code' => 'R9-CSTMR-00151',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 31,
                'classification_id' => 8,
                'name_id' => 131,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-29 19:12:12',
                'updated_at' => '2024-08-29 19:12:12',
            ),
            151 => 
            array (
                'id' => 153,
                'code' => 'R9-CSTMR-00152',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 8,
                'name_id' => 132,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-29 19:13:18',
                'updated_at' => '2024-08-29 19:13:18',
            ),
            152 => 
            array (
                'id' => 154,
                'code' => 'R9-CSTMR-00153',
                'name' => 'San Jose Gusu',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 8,
                'name_id' => 133,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-29 19:15:36',
                'updated_at' => '2024-08-29 19:15:36',
            ),
            153 => 
            array (
                'id' => 155,
                'code' => 'R9-CSTMR-00154',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 31,
                'classification_id' => 8,
                'name_id' => 134,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-29 19:17:05',
                'updated_at' => '2024-08-29 19:17:05',
            ),
            154 => 
            array (
                'id' => 156,
                'code' => 'R9-CSTMR-00155',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 8,
                'name_id' => 135,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-29 19:18:18',
                'updated_at' => '2024-08-29 19:18:18',
            ),
            155 => 
            array (
                'id' => 157,
                'code' => 'R9-CSTMR-00156',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 84,
                'classification_id' => 8,
                'name_id' => 136,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-31 10:48:06',
                'updated_at' => '2024-08-31 10:48:06',
            ),
            156 => 
            array (
                'id' => 158,
                'code' => 'R9-CSTMR-00157',
                'name' => 'Warehouse',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 95,
                'classification_id' => 8,
                'name_id' => 88,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-31 11:42:34',
                'updated_at' => '2024-08-31 11:42:34',
            ),
            157 => 
            array (
                'id' => 159,
                'code' => 'R9-CSTMR-00158',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 31,
                'classification_id' => 8,
                'name_id' => 137,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-08-31 11:47:27',
                'updated_at' => '2024-08-31 11:47:27',
            ),
            158 => 
            array (
                'id' => 160,
                'code' => 'R9-CSTMR-00159',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 16,
                'classification_id' => 8,
                'name_id' => 138,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-09-02 15:10:28',
                'updated_at' => '2024-09-02 15:10:28',
            ),
            159 => 
            array (
                'id' => 161,
                'code' => 'R9-CSTMR-00160',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 107,
                'classification_id' => 9,
                'name_id' => 139,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-09-02 15:12:13',
                'updated_at' => '2024-09-02 15:12:13',
            ),
            160 => 
            array (
                'id' => 162,
                'code' => 'R9-CSTMR-00161',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 8,
                'name_id' => 140,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-09-02 15:22:53',
                'updated_at' => '2024-09-02 15:22:53',
            ),
            161 => 
            array (
                'id' => 163,
                'code' => 'R9-CSTMR-00162',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 8,
                'name_id' => 141,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-09-02 15:29:15',
                'updated_at' => '2024-09-02 15:29:15',
            ),
        ));

        
    }
}