<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CustomersTableSeeder extends Seeder
{
    /**
     * Auto generated seeder file.
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('customers')->delete();
        
        \DB::table('customers')->insert(array (
            0 => 
            array (
                'id' => 2,
                'code' => 'R9-CSTMR-00001',
                'name' => 'Dressing Plant',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 23,
                'classification_id' => 74,
                'name_id' => 2,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 13:35:41',
                'updated_at' => '2024-07-30 13:35:41',
            ),
            1 => 
            array (
                'id' => 3,
                'code' => 'R9-CSTMR-00002',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 25,
                'classification_id' => 74,
                'name_id' => 3,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 13:48:15',
                'updated_at' => '2024-07-30 13:48:15',
            ),
            2 => 
            array (
                'id' => 4,
                'code' => 'R9-CSTMR-00003',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 16,
                'classification_id' => 74,
                'name_id' => 6,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 13:57:10',
                'updated_at' => '2024-07-30 13:57:10',
            ),
            3 => 
            array (
                'id' => 5,
                'code' => 'R9-CSTMR-00004',
                'name' => 'Isabela City',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 22,
                'classification_id' => 74,
                'name_id' => 7,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 14:02:23',
                'updated_at' => '2024-07-30 14:02:23',
            ),
            4 => 
            array (
                'id' => 6,
                'code' => 'R9-CSTMR-00005',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 22,
                'classification_id' => 74,
                'name_id' => 8,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 14:05:08',
                'updated_at' => '2024-07-30 14:05:08',
            ),
            5 => 
            array (
                'id' => 7,
                'code' => 'R9-CSTMR-00006',
                'name' => 'Microbiological Laboratory',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 22,
                'classification_id' => 74,
                'name_id' => 9,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 14:08:45',
                'updated_at' => '2024-07-30 14:08:45',
            ),
            6 => 
            array (
                'id' => 8,
                'code' => 'R9-CSTMR-00007',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 95,
                'classification_id' => 74,
                'name_id' => 10,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 14:12:39',
                'updated_at' => '2024-07-30 14:12:39',
            ),
            7 => 
            array (
                'id' => 9,
                'code' => 'R9-CSTMR-00008',
                'name' => 'Metrology Laboratory',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 22,
                'classification_id' => 74,
                'name_id' => 9,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 14:14:49',
                'updated_at' => '2024-07-30 14:14:49',
            ),
            8 => 
            array (
                'id' => 10,
                'code' => 'R9-CSTMR-00009',
                'name' => 'Chemical Laboratory',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 22,
                'classification_id' => 74,
                'name_id' => 9,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 14:16:09',
                'updated_at' => '2024-07-30 14:16:09',
            ),
            9 => 
            array (
                'id' => 11,
                'code' => 'R9-CSTMR-00010',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 31,
                'classification_id' => 74,
                'name_id' => 11,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 14:24:37',
                'updated_at' => '2024-07-30 14:24:37',
            ),
            10 => 
            array (
                'id' => 12,
                'code' => 'R9-CSTMR-00011',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 31,
                'classification_id' => 74,
                'name_id' => 12,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 14:27:56',
                'updated_at' => '2024-07-30 14:27:56',
            ),
            11 => 
            array (
                'id' => 13,
                'code' => 'R9-CSTMR-00012',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 95,
                'classification_id' => 74,
                'name_id' => 13,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 14:31:01',
                'updated_at' => '2024-07-30 14:31:01',
            ),
            12 => 
            array (
                'id' => 14,
                'code' => 'R9-CSTMR-00013',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 54,
                'classification_id' => 74,
                'name_id' => 14,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 14:55:55',
                'updated_at' => '2024-07-30 14:55:55',
            ),
            13 => 
            array (
                'id' => 15,
                'code' => 'R9-CSTMR-00014',
                'name' => 'R.T Lim',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 22,
                'classification_id' => 74,
                'name_id' => 15,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 14:58:27',
                'updated_at' => '2024-07-30 14:58:27',
            ),
            14 => 
            array (
                'id' => 16,
                'code' => 'R9-CSTMR-00015',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 25,
                'classification_id' => 74,
                'name_id' => 16,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:00:14',
                'updated_at' => '2024-07-30 15:00:14',
            ),
            15 => 
            array (
                'id' => 17,
                'code' => 'R9-CSTMR-00016',
                'name' => 'Western Mindanao Regional Office IX',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 22,
                'classification_id' => 74,
                'name_id' => 17,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:02:14',
                'updated_at' => '2024-07-30 15:02:14',
            ),
            16 => 
            array (
                'id' => 18,
                'code' => 'R9-CSTMR-00017',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 95,
                'classification_id' => 74,
                'name_id' => 18,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:03:40',
                'updated_at' => '2024-07-30 15:03:40',
            ),
            17 => 
            array (
                'id' => 19,
                'code' => 'R9-CSTMR-00018',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 25,
                'classification_id' => 74,
                'name_id' => 19,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:05:39',
                'updated_at' => '2024-07-30 15:05:39',
            ),
            18 => 
            array (
                'id' => 20,
                'code' => 'R9-CSTMR-00019',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 74,
                'name_id' => 20,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:08:30',
                'updated_at' => '2024-07-30 15:08:30',
            ),
            19 => 
            array (
                'id' => 21,
                'code' => 'R9-CSTMR-00020',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 107,
                'classification_id' => 73,
                'name_id' => 21,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:11:24',
                'updated_at' => '2024-07-30 15:11:24',
            ),
            20 => 
            array (
                'id' => 22,
                'code' => 'R9-CSTMR-00021',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 25,
                'classification_id' => 74,
                'name_id' => 22,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:13:55',
                'updated_at' => '2024-07-30 15:13:55',
            ),
            21 => 
            array (
                'id' => 23,
                'code' => 'R9-CSTMR-00022',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 25,
                'classification_id' => 74,
                'name_id' => 23,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:16:22',
                'updated_at' => '2024-07-30 15:16:22',
            ),
            22 => 
            array (
                'id' => 24,
                'code' => 'R9-CSTMR-00023',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 25,
                'classification_id' => 74,
                'name_id' => 24,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:17:55',
                'updated_at' => '2024-07-30 15:17:55',
            ),
            23 => 
            array (
                'id' => 25,
                'code' => 'R9-CSTMR-00024',
                'name' => 'Rizal Avenue',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 41,
                'classification_id' => 74,
                'name_id' => 25,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:20:39',
                'updated_at' => '2024-07-30 15:20:39',
            ),
            24 => 
            array (
                'id' => 26,
                'code' => 'R9-CSTMR-00025',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 25,
                'classification_id' => 74,
                'name_id' => 26,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:23:05',
                'updated_at' => '2024-07-30 15:23:05',
            ),
            25 => 
            array (
                'id' => 27,
                'code' => 'R9-CSTMR-00026',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 12,
                'classification_id' => 74,
                'name_id' => 27,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:25:53',
                'updated_at' => '2024-07-30 15:25:53',
            ),
            26 => 
            array (
                'id' => 28,
                'code' => 'R9-CSTMR-00027',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 67,
                'classification_id' => 74,
                'name_id' => 28,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:28:12',
                'updated_at' => '2024-07-30 15:28:12',
            ),
            27 => 
            array (
                'id' => 29,
                'code' => 'R9-CSTMR-00028',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 25,
                'classification_id' => 74,
                'name_id' => 29,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:30:29',
                'updated_at' => '2024-07-30 15:30:29',
            ),
            28 => 
            array (
                'id' => 30,
                'code' => 'R9-CSTMR-00029',
                'name' => 'Titay Plant',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 74,
                'name_id' => 30,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:32:52',
                'updated_at' => '2024-07-30 15:32:52',
            ),
            29 => 
            array (
                'id' => 31,
                'code' => 'R9-CSTMR-00030',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 74,
                'name_id' => 31,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:34:51',
                'updated_at' => '2024-07-30 15:34:51',
            ),
            30 => 
            array (
                'id' => 32,
                'code' => 'R9-CSTMR-00031',
                'name' => 'Region IX',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 22,
                'classification_id' => 74,
                'name_id' => 32,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:40:12',
                'updated_at' => '2024-07-30 15:40:12',
            ),
            31 => 
            array (
                'id' => 33,
                'code' => 'R9-CSTMR-00032',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 74,
                'name_id' => 33,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:42:45',
                'updated_at' => '2024-07-30 15:42:45',
            ),
            32 => 
            array (
                'id' => 34,
                'code' => 'R9-CSTMR-00033',
                'name' => 'Mindanao Livestock Production Center',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 23,
                'classification_id' => 74,
                'name_id' => 34,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:46:18',
                'updated_at' => '2024-07-30 15:46:18',
            ),
            33 => 
            array (
                'id' => 35,
                'code' => 'R9-CSTMR-00034',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 56,
                'classification_id' => 74,
                'name_id' => 35,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:47:49',
                'updated_at' => '2024-07-30 15:47:49',
            ),
            34 => 
            array (
                'id' => 36,
                'code' => 'R9-CSTMR-00035',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 96,
                'classification_id' => 74,
                'name_id' => 36,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:49:30',
                'updated_at' => '2024-07-30 15:49:30',
            ),
            35 => 
            array (
                'id' => 37,
                'code' => 'R9-CSTMR-00036',
                'name' => 'Greenwhich Camins',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 72,
                'classification_id' => 74,
                'name_id' => 37,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:52:41',
                'updated_at' => '2024-07-30 15:52:41',
            ),
            36 => 
            array (
                'id' => 38,
                'code' => 'R9-CSTMR-00037',
                'name' => 'Greenwich Ipil',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 72,
                'classification_id' => 74,
                'name_id' => 38,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:55:53',
                'updated_at' => '2024-07-30 15:55:53',
            ),
            37 => 
            array (
                'id' => 39,
                'code' => 'R9-CSTMR-00038',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 74,
                'name_id' => 39,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 15:59:51',
                'updated_at' => '2024-07-30 15:59:51',
            ),
            38 => 
            array (
                'id' => 40,
                'code' => 'R9-CSTMR-00039',
                'name' => 'Western Mindanao',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 74,
                'name_id' => 30,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:06:20',
                'updated_at' => '2024-07-30 16:06:20',
            ),
            39 => 
            array (
                'id' => 41,
                'code' => 'R9-CSTMR-00040',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 12,
                'classification_id' => 74,
                'name_id' => 40,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:11:41',
                'updated_at' => '2024-07-30 16:11:41',
            ),
            40 => 
            array (
                'id' => 42,
                'code' => 'R9-CSTMR-00041',
                'name' => 'Tetuan',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 95,
                'classification_id' => 74,
                'name_id' => 41,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:13:23',
                'updated_at' => '2024-07-30 16:13:23',
            ),
            41 => 
            array (
                'id' => 43,
                'code' => 'R9-CSTMR-00042',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 60,
                'classification_id' => 74,
                'name_id' => 42,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:15:08',
                'updated_at' => '2024-07-30 16:15:08',
            ),
            42 => 
            array (
                'id' => 44,
                'code' => 'R9-CSTMR-00043',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 56,
                'classification_id' => 74,
                'name_id' => 43,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:16:59',
                'updated_at' => '2024-07-30 16:16:59',
            ),
            43 => 
            array (
                'id' => 45,
                'code' => 'R9-CSTMR-00044',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 42,
                'classification_id' => 74,
                'name_id' => 44,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:20:12',
                'updated_at' => '2024-07-30 16:20:12',
            ),
            44 => 
            array (
                'id' => 46,
                'code' => 'R9-CSTMR-00045',
                'name' => 'Culianan',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 95,
                'classification_id' => 73,
                'name_id' => 41,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:21:41',
                'updated_at' => '2024-07-30 16:21:41',
            ),
            45 => 
            array (
                'id' => 47,
                'code' => 'R9-CSTMR-00046',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 71,
                'classification_id' => 74,
                'name_id' => 45,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:23:56',
                'updated_at' => '2024-07-30 16:23:56',
            ),
            46 => 
            array (
                'id' => 48,
                'code' => 'R9-CSTMR-00047',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 72,
                'classification_id' => 74,
                'name_id' => 46,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:25:43',
                'updated_at' => '2024-07-30 16:25:43',
            ),
            47 => 
            array (
                'id' => 49,
                'code' => 'R9-CSTMR-00048',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 25,
                'classification_id' => 74,
                'name_id' => 47,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:27:32',
                'updated_at' => '2024-07-30 16:27:32',
            ),
            48 => 
            array (
                'id' => 50,
                'code' => 'R9-CSTMR-00049',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 84,
                'classification_id' => 74,
                'name_id' => 48,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:29:49',
                'updated_at' => '2024-07-30 16:29:49',
            ),
            49 => 
            array (
                'id' => 51,
                'code' => 'R9-CSTMR-00050',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 72,
                'classification_id' => 74,
                'name_id' => 49,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:34:00',
                'updated_at' => '2024-07-30 16:34:00',
            ),
            50 => 
            array (
                'id' => 52,
                'code' => 'R9-CSTMR-00051',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 95,
                'classification_id' => 74,
                'name_id' => 50,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:35:34',
                'updated_at' => '2024-07-30 16:35:34',
            ),
            51 => 
            array (
                'id' => 53,
                'code' => 'R9-CSTMR-00052',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 103,
                'classification_id' => 74,
                'name_id' => 51,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:36:48',
                'updated_at' => '2024-07-30 16:36:48',
            ),
            52 => 
            array (
                'id' => 54,
                'code' => 'R9-CSTMR-00053',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 104,
                'classification_id' => 74,
                'name_id' => 52,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:39:02',
                'updated_at' => '2024-07-30 16:39:02',
            ),
            53 => 
            array (
                'id' => 55,
                'code' => 'R9-CSTMR-00054',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 71,
                'classification_id' => 74,
                'name_id' => 53,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:40:28',
                'updated_at' => '2024-07-30 16:40:28',
            ),
            54 => 
            array (
                'id' => 56,
                'code' => 'R9-CSTMR-00055',
                'name' => 'Jollibee Basilan',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 72,
                'classification_id' => 74,
                'name_id' => 54,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:41:53',
                'updated_at' => '2024-07-30 16:41:53',
            ),
            55 => 
            array (
                'id' => 57,
                'code' => 'R9-CSTMR-00056',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 104,
                'classification_id' => 74,
                'name_id' => 55,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:43:08',
                'updated_at' => '2024-07-30 16:43:08',
            ),
            56 => 
            array (
                'id' => 58,
                'code' => 'R9-CSTMR-00057',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 56,
                'classification_id' => 74,
                'name_id' => 56,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:44:17',
                'updated_at' => '2024-07-30 16:44:17',
            ),
            57 => 
            array (
                'id' => 59,
                'code' => 'R9-CSTMR-00058',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 25,
                'classification_id' => 74,
                'name_id' => 57,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:47:53',
                'updated_at' => '2024-07-30 16:47:53',
            ),
            58 => 
            array (
                'id' => 60,
                'code' => 'R9-CSTMR-00059',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 56,
                'classification_id' => 74,
                'name_id' => 58,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:48:58',
                'updated_at' => '2024-07-30 16:48:58',
            ),
            59 => 
            array (
                'id' => 61,
                'code' => 'R9-CSTMR-00060',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 25,
                'classification_id' => 74,
                'name_id' => 59,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:50:15',
                'updated_at' => '2024-07-30 16:50:15',
            ),
            60 => 
            array (
                'id' => 62,
                'code' => 'R9-CSTMR-00061',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 72,
                'classification_id' => 74,
                'name_id' => 60,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:54:24',
                'updated_at' => '2024-07-30 16:54:24',
            ),
            61 => 
            array (
                'id' => 63,
                'code' => 'R9-CSTMR-00062',
                'name' => 'Zamboanga Station',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 68,
                'classification_id' => 74,
                'name_id' => 61,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:56:37',
                'updated_at' => '2024-07-30 16:56:37',
            ),
            62 => 
            array (
                'id' => 64,
                'code' => 'R9-CSTMR-00063',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 74,
                'name_id' => 62,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:58:37',
                'updated_at' => '2024-07-30 16:58:37',
            ),
            63 => 
            array (
                'id' => 65,
                'code' => 'R9-CSTMR-00064',
                'name' => 'Main',
                'is_main' => 1,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 25,
                'classification_id' => 74,
                'name_id' => 63,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 16:59:47',
                'updated_at' => '2024-07-30 16:59:47',
            ),
            64 => 
            array (
                'id' => 66,
                'code' => 'R9-CSTMR-00065',
                'name' => 'Dipolog Branch',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 74,
                'name_id' => 64,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 17:01:11',
                'updated_at' => '2024-07-30 17:01:11',
            ),
            65 => 
            array (
                'id' => 67,
                'code' => 'R9-CSTMR-00066',
                'name' => 'Piñan Branch',
                'is_main' => 0,
                'is_internal' => 0,
                'is_active' => 1,
                'industry_id' => 4,
                'classification_id' => 74,
                'name_id' => 64,
                'laboratory_id' => 14,
                'user_id' => 2,
                'created_at' => '2024-07-30 17:02:26',
                'updated_at' => '2024-07-30 17:02:26',
            ),
        ));

        
    }
}