<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TsrPaymentsTableSeeder extends Seeder
{
    /**
     * Auto generated seeder file.
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tsr_payments')->delete();
        
        \DB::table('tsr_payments')->insert(array (
            0 => 
            array (
                'id' => 1,
                'total' => '10750.00',
                'subtotal' => '11250.00',
                'discount' => '0.00',
                'or_number' => '86989',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 1,
                'discount_id' => 1,
                'payment_id' => 18,
                'collection_id' => 25,
                'status_id' => 7,
                'tsr_id' => 1,
                'paid_at' => '2024-08-16 09:10:25',
            ),
            1 => 
            array (
                'id' => 2,
                'total' => '0.00',
                'subtotal' => '22500.00',
                'discount' => '22500.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 1,
                'has_deduction' => 0,
                'discount_id' => 6,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 8,
                'tsr_id' => 2,
                'paid_at' => '2024-08-16 09:16:20',
            ),
            2 => 
            array (
                'id' => 3,
                'total' => '2200.00',
                'subtotal' => '2200.00',
                'discount' => '0.00',
                'or_number' => '86982',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 25,
                'status_id' => 7,
                'tsr_id' => 3,
                'paid_at' => '2024-08-17 17:53:04',
            ),
            3 => 
            array (
                'id' => 4,
                'total' => '1000.00',
                'subtotal' => '1000.00',
                'discount' => '0.00',
                'or_number' => '86992',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 24,
                'status_id' => 7,
                'tsr_id' => 4,
                'paid_at' => '2024-08-19 08:51:41',
            ),
            4 => 
            array (
                'id' => 5,
                'total' => '600.00',
                'subtotal' => '600.00',
                'discount' => '0.00',
                'or_number' => '86985',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 25,
                'status_id' => 7,
                'tsr_id' => 5,
                'paid_at' => '2024-08-17 17:54:39',
            ),
            5 => 
            array (
                'id' => 6,
                'total' => '1650.00',
                'subtotal' => '1650.00',
                'discount' => '0.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 18,
                'tsr_id' => 6,
                'paid_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'total' => '2053.00',
                'subtotal' => '2053.00',
                'discount' => '0.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 18,
                'tsr_id' => 7,
                'paid_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'total' => '7570.00',
                'subtotal' => '7570.00',
                'discount' => '0.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 18,
                'tsr_id' => 8,
                'paid_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'total' => '1650.00',
                'subtotal' => '1650.00',
                'discount' => '0.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 18,
                'tsr_id' => 9,
                'paid_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'total' => '2053.00',
                'subtotal' => '2053.00',
                'discount' => '0.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 18,
                'tsr_id' => 10,
                'paid_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'total' => '7570.00',
                'subtotal' => '7570.00',
                'discount' => '0.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 18,
                'tsr_id' => 11,
                'paid_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'total' => '1650.00',
                'subtotal' => '1650.00',
                'discount' => '0.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 18,
                'tsr_id' => 12,
                'paid_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'total' => '2053.00',
                'subtotal' => '2053.00',
                'discount' => '0.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 18,
                'tsr_id' => 13,
                'paid_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'total' => '7570.00',
                'subtotal' => '7570.00',
                'discount' => '0.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 18,
                'tsr_id' => 14,
                'paid_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'total' => '1650.00',
                'subtotal' => '1650.00',
                'discount' => '0.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 18,
                'tsr_id' => 15,
                'paid_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'total' => '2053.00',
                'subtotal' => '2053.00',
                'discount' => '0.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 18,
                'tsr_id' => 16,
                'paid_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'total' => '7570.00',
                'subtotal' => '7570.00',
                'discount' => '0.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 18,
                'tsr_id' => 17,
                'paid_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'total' => '1650.00',
                'subtotal' => '1650.00',
                'discount' => '0.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 18,
                'tsr_id' => 18,
                'paid_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'total' => '2053.00',
                'subtotal' => '2053.00',
                'discount' => '0.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 18,
                'tsr_id' => 19,
                'paid_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'total' => '7570.00',
                'subtotal' => '7570.00',
                'discount' => '0.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 18,
                'tsr_id' => 20,
                'paid_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'total' => '1650.00',
                'subtotal' => '1650.00',
                'discount' => '0.00',
                'or_number' => '86984',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 25,
                'status_id' => 7,
                'tsr_id' => 21,
                'paid_at' => '2024-08-17 17:54:05',
            ),
            21 => 
            array (
                'id' => 22,
                'total' => '2100.00',
                'subtotal' => '2100.00',
                'discount' => '0.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 18,
                'tsr_id' => 22,
                'paid_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'total' => '500.00',
                'subtotal' => '500.00',
                'discount' => '0.00',
                'or_number' => '86986',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 24,
                'status_id' => 7,
                'tsr_id' => 23,
                'paid_at' => '2024-08-17 17:54:53',
            ),
            23 => 
            array (
                'id' => 24,
                'total' => '1475.00',
                'subtotal' => '1475.00',
                'discount' => '0.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 18,
                'tsr_id' => 24,
                'paid_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'total' => '7570.00',
                'subtotal' => '7570.00',
                'discount' => '0.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 18,
                'tsr_id' => 25,
                'paid_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'total' => '2400.00',
                'subtotal' => '2400.00',
                'discount' => '0.00',
                'or_number' => '86987',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 24,
                'status_id' => 7,
                'tsr_id' => 26,
                'paid_at' => '2024-08-17 17:55:06',
            ),
            26 => 
            array (
                'id' => 27,
                'total' => '2400.00',
                'subtotal' => '2400.00',
                'discount' => '0.00',
                'or_number' => '86988',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 24,
                'status_id' => 7,
                'tsr_id' => 27,
                'paid_at' => '2024-08-17 17:55:28',
            ),
            27 => 
            array (
                'id' => 28,
                'total' => '1650.00',
                'subtotal' => '1650.00',
                'discount' => '0.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 18,
                'tsr_id' => 28,
                'paid_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'total' => '1475.00',
                'subtotal' => '1475.00',
                'discount' => '0.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 18,
                'tsr_id' => 29,
                'paid_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'total' => '7570.00',
                'subtotal' => '7570.00',
                'discount' => '0.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 18,
                'tsr_id' => 30,
                'paid_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'total' => '2650.00',
                'subtotal' => '2650.00',
                'discount' => '0.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 18,
                'tsr_id' => 31,
                'paid_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'total' => '1475.00',
                'subtotal' => '1475.00',
                'discount' => '0.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 18,
                'tsr_id' => 32,
                'paid_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'total' => '7570.00',
                'subtotal' => '7570.00',
                'discount' => '0.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 18,
                'tsr_id' => 33,
                'paid_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'total' => '1000.00',
                'subtotal' => '1000.00',
                'discount' => '0.00',
                'or_number' => '86994',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 25,
                'status_id' => 7,
                'tsr_id' => 34,
                'paid_at' => '2024-08-19 08:53:41',
            ),
            34 => 
            array (
                'id' => 35,
                'total' => '2000.00',
                'subtotal' => '2000.00',
                'discount' => '0.00',
                'or_number' => '86995',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 25,
                'status_id' => 7,
                'tsr_id' => 35,
                'paid_at' => '2024-08-19 08:53:52',
            ),
            35 => 
            array (
                'id' => 36,
                'total' => '3100.00',
                'subtotal' => '3100.00',
                'discount' => '0.00',
                'or_number' => '86996',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 25,
                'status_id' => 7,
                'tsr_id' => 36,
                'paid_at' => '2024-08-19 08:54:07',
            ),
            36 => 
            array (
                'id' => 37,
                'total' => '850.00',
                'subtotal' => '850.00',
                'discount' => '0.00',
                'or_number' => '86997',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 24,
                'status_id' => 7,
                'tsr_id' => 37,
                'paid_at' => '2024-08-19 08:54:15',
            ),
            37 => 
            array (
                'id' => 38,
                'total' => '8612.00',
                'subtotal' => '10765.00',
                'discount' => '2153.00',
                'or_number' => '87011',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 2,
                'payment_id' => 17,
                'collection_id' => 25,
                'status_id' => 7,
                'tsr_id' => 38,
                'paid_at' => '2024-08-19 09:00:15',
            ),
            38 => 
            array (
                'id' => 39,
                'total' => '9300.00',
                'subtotal' => '9300.00',
                'discount' => '0.00',
                'or_number' => '86998',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 25,
                'status_id' => 7,
                'tsr_id' => 39,
                'paid_at' => '2024-08-19 08:54:21',
            ),
            39 => 
            array (
                'id' => 41,
                'total' => '550.00',
                'subtotal' => '550.00',
                'discount' => '0.00',
                'or_number' => '87005',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 18,
                'collection_id' => 25,
                'status_id' => 7,
                'tsr_id' => 41,
                'paid_at' => '2024-08-19 08:58:35',
            ),
            40 => 
            array (
                'id' => 42,
                'total' => '6550.00',
                'subtotal' => '6550.00',
                'discount' => '0.00',
                'or_number' => '87005',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 18,
                'collection_id' => 25,
                'status_id' => 7,
                'tsr_id' => 42,
                'paid_at' => '2024-08-19 08:58:35',
            ),
            41 => 
            array (
                'id' => 43,
                'total' => '2100.00',
                'subtotal' => '2100.00',
                'discount' => '0.00',
                'or_number' => '87000',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 25,
                'status_id' => 7,
                'tsr_id' => 43,
                'paid_at' => '2024-08-19 08:55:33',
            ),
            42 => 
            array (
                'id' => 44,
                'total' => '0.00',
                'subtotal' => '3000.00',
                'discount' => '3000.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 1,
                'has_deduction' => 0,
                'discount_id' => 6,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 8,
                'tsr_id' => 44,
                'paid_at' => '2024-08-16 17:21:14',
            ),
            43 => 
            array (
                'id' => 45,
                'total' => '6000.00',
                'subtotal' => '6000.00',
                'discount' => '0.00',
                'or_number' => '87003',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 18,
                'collection_id' => 25,
                'status_id' => 7,
                'tsr_id' => 45,
                'paid_at' => '2024-08-19 08:56:40',
            ),
            44 => 
            array (
                'id' => 46,
                'total' => '2000.00',
                'subtotal' => '2000.00',
                'discount' => '0.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 5,
                'tsr_id' => 46,
                'paid_at' => NULL,
            ),
            45 => 
            array (
                'id' => 47,
                'total' => '0.00',
                'subtotal' => '4950.00',
                'discount' => '4950.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 1,
                'has_deduction' => 0,
                'discount_id' => 6,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 8,
                'tsr_id' => 47,
                'paid_at' => '2024-08-16 20:50:54',
            ),
            46 => 
            array (
                'id' => 48,
                'total' => '2500.00',
                'subtotal' => '2500.00',
                'discount' => '0.00',
                'or_number' => '87001',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 25,
                'status_id' => 7,
                'tsr_id' => 48,
                'paid_at' => '2024-08-19 08:55:50',
            ),
            47 => 
            array (
                'id' => 49,
                'total' => '21420.00',
                'subtotal' => '21420.00',
                'discount' => '0.00',
                'or_number' => '86999',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 24,
                'status_id' => 7,
                'tsr_id' => 49,
                'paid_at' => '2024-08-19 08:55:08',
            ),
            48 => 
            array (
                'id' => 50,
                'total' => '3300.00',
                'subtotal' => '3300.00',
                'discount' => '0.00',
                'or_number' => '87002',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 25,
                'status_id' => 7,
                'tsr_id' => 50,
                'paid_at' => '2024-08-19 08:55:56',
            ),
            49 => 
            array (
                'id' => 51,
                'total' => '17600.00',
                'subtotal' => '17600.00',
                'discount' => '0.00',
                'or_number' => '87002',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 25,
                'status_id' => 7,
                'tsr_id' => 51,
                'paid_at' => '2024-08-19 08:55:56',
            ),
            50 => 
            array (
                'id' => 52,
                'total' => '0.00',
                'subtotal' => '1080.00',
                'discount' => '1080.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 1,
                'has_deduction' => 0,
                'discount_id' => 7,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 8,
                'tsr_id' => 52,
                'paid_at' => '2024-08-16 21:24:42',
            ),
            51 => 
            array (
                'id' => 53,
                'total' => '1550.00',
                'subtotal' => '1550.00',
                'discount' => '0.00',
                'or_number' => '87004',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 24,
                'status_id' => 7,
                'tsr_id' => 53,
                'paid_at' => '2024-08-19 08:57:04',
            ),
            52 => 
            array (
                'id' => 54,
                'total' => '4000.00',
                'subtotal' => '4000.00',
                'discount' => '0.00',
                'or_number' => '87006',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 24,
                'status_id' => 7,
                'tsr_id' => 54,
                'paid_at' => '2024-08-19 08:59:05',
            ),
            53 => 
            array (
                'id' => 55,
                'total' => '1000.00',
                'subtotal' => '1000.00',
                'discount' => '0.00',
                'or_number' => '87007',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 25,
                'status_id' => 7,
                'tsr_id' => 55,
                'paid_at' => '2024-08-19 08:59:14',
            ),
            54 => 
            array (
                'id' => 56,
                'total' => '6920.00',
                'subtotal' => '6920.00',
                'discount' => '0.00',
                'or_number' => '87007',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 25,
                'status_id' => 7,
                'tsr_id' => 56,
                'paid_at' => '2024-08-19 08:59:14',
            ),
            55 => 
            array (
                'id' => 57,
                'total' => '500.00',
                'subtotal' => '500.00',
                'discount' => '0.00',
                'or_number' => '87008',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 24,
                'status_id' => 7,
                'tsr_id' => 57,
                'paid_at' => '2024-08-19 08:59:21',
            ),
            56 => 
            array (
                'id' => 58,
                'total' => '1550.00',
                'subtotal' => '1550.00',
                'discount' => '0.00',
                'or_number' => '87009',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 24,
                'status_id' => 7,
                'tsr_id' => 58,
                'paid_at' => '2024-08-19 08:59:40',
            ),
            57 => 
            array (
                'id' => 59,
                'total' => '0.00',
                'subtotal' => '27700.00',
                'discount' => '27700.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 1,
                'has_deduction' => 0,
                'discount_id' => 6,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 8,
                'tsr_id' => 59,
                'paid_at' => '2024-08-16 23:24:20',
            ),
            58 => 
            array (
                'id' => 61,
                'total' => '1700.00',
                'subtotal' => '1700.00',
                'discount' => '0.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 9,
                'tsr_id' => 61,
                'paid_at' => NULL,
            ),
            59 => 
            array (
                'id' => 62,
                'total' => '800.00',
                'subtotal' => '800.00',
                'discount' => '0.00',
                'or_number' => '87010',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 25,
                'status_id' => 7,
                'tsr_id' => 62,
                'paid_at' => '2024-08-19 08:59:54',
            ),
            60 => 
            array (
                'id' => 63,
                'total' => '1750.00',
                'subtotal' => '1750.00',
                'discount' => '0.00',
                'or_number' => '87017',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 24,
                'status_id' => 7,
                'tsr_id' => 63,
                'paid_at' => '2024-08-19 09:03:07',
            ),
            61 => 
            array (
                'id' => 64,
                'total' => '1550.00',
                'subtotal' => '1550.00',
                'discount' => '0.00',
                'or_number' => '87012',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 24,
                'status_id' => 7,
                'tsr_id' => 64,
                'paid_at' => '2024-08-19 09:00:41',
            ),
            62 => 
            array (
                'id' => 65,
                'total' => '1550.00',
                'subtotal' => '1550.00',
                'discount' => '0.00',
                'or_number' => '87013',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 24,
                'status_id' => 7,
                'tsr_id' => 65,
                'paid_at' => '2024-08-19 09:00:57',
            ),
            63 => 
            array (
                'id' => 66,
                'total' => '4650.00',
                'subtotal' => '4650.00',
                'discount' => '0.00',
                'or_number' => '87014',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 25,
                'status_id' => 7,
                'tsr_id' => 66,
                'paid_at' => '2024-08-19 09:01:16',
            ),
            64 => 
            array (
                'id' => 67,
                'total' => '1550.00',
                'subtotal' => '1550.00',
                'discount' => '0.00',
                'or_number' => '87022',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 24,
                'status_id' => 7,
                'tsr_id' => 67,
                'paid_at' => '2024-08-19 09:04:18',
            ),
            65 => 
            array (
                'id' => 68,
                'total' => '3750.00',
                'subtotal' => '3750.00',
                'discount' => '0.00',
                'or_number' => '87015',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 18,
                'collection_id' => 25,
                'status_id' => 7,
                'tsr_id' => 68,
                'paid_at' => '2024-08-19 09:01:59',
            ),
            66 => 
            array (
                'id' => 69,
                'total' => '4200.00',
                'subtotal' => '4200.00',
                'discount' => '0.00',
                'or_number' => '87015',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 18,
                'collection_id' => 25,
                'status_id' => 7,
                'tsr_id' => 69,
                'paid_at' => '2024-08-19 09:01:59',
            ),
            67 => 
            array (
                'id' => 70,
                'total' => '500.00',
                'subtotal' => '500.00',
                'discount' => '0.00',
                'or_number' => '87016',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 24,
                'status_id' => 7,
                'tsr_id' => 70,
                'paid_at' => '2024-08-19 09:02:24',
            ),
            68 => 
            array (
                'id' => 71,
                'total' => '900.00',
                'subtotal' => '900.00',
                'discount' => '0.00',
                'or_number' => '87018',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 24,
                'status_id' => 7,
                'tsr_id' => 71,
                'paid_at' => '2024-08-19 09:03:19',
            ),
            69 => 
            array (
                'id' => 72,
                'total' => '1550.00',
                'subtotal' => '1550.00',
                'discount' => '0.00',
                'or_number' => '87019',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 24,
                'status_id' => 7,
                'tsr_id' => 72,
                'paid_at' => '2024-08-19 09:03:48',
            ),
            70 => 
            array (
                'id' => 73,
                'total' => '6920.00',
                'subtotal' => '6920.00',
                'discount' => '0.00',
                'or_number' => '87020',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 25,
                'status_id' => 7,
                'tsr_id' => 73,
                'paid_at' => '2024-08-19 09:03:56',
            ),
            71 => 
            array (
                'id' => 74,
                'total' => '1500.00',
                'subtotal' => '1500.00',
                'discount' => '0.00',
                'or_number' => '87021',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 25,
                'status_id' => 7,
                'tsr_id' => 74,
                'paid_at' => '2024-08-19 09:04:09',
            ),
            72 => 
            array (
                'id' => 75,
                'total' => '1550.00',
                'subtotal' => '1550.00',
                'discount' => '0.00',
                'or_number' => '87024',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 24,
                'status_id' => 7,
                'tsr_id' => 75,
                'paid_at' => '2024-08-19 09:04:44',
            ),
            73 => 
            array (
                'id' => 76,
                'total' => '1550.00',
                'subtotal' => '1550.00',
                'discount' => '0.00',
                'or_number' => '87025',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 24,
                'status_id' => 7,
                'tsr_id' => 76,
                'paid_at' => '2024-08-19 09:04:57',
            ),
            74 => 
            array (
                'id' => 77,
                'total' => '1550.00',
                'subtotal' => '1550.00',
                'discount' => '0.00',
                'or_number' => '87023',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 24,
                'status_id' => 7,
                'tsr_id' => 77,
                'paid_at' => '2024-08-19 09:04:38',
            ),
            75 => 
            array (
                'id' => 78,
                'total' => '550.00',
                'subtotal' => '550.00',
                'discount' => '0.00',
                'or_number' => '87026',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 25,
                'status_id' => 7,
                'tsr_id' => 78,
                'paid_at' => '2024-08-19 09:05:18',
            ),
            76 => 
            array (
                'id' => 79,
                'total' => '6525.00',
                'subtotal' => '6525.00',
                'discount' => '0.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 6,
                'tsr_id' => 79,
                'paid_at' => NULL,
            ),
            77 => 
            array (
                'id' => 80,
                'total' => '0.00',
                'subtotal' => '2100.00',
                'discount' => '2100.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 1,
                'has_deduction' => 0,
                'discount_id' => 6,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 8,
                'tsr_id' => 80,
                'paid_at' => '2024-08-17 17:13:59',
            ),
            78 => 
            array (
                'id' => 81,
                'total' => '500.00',
                'subtotal' => '500.00',
                'discount' => '0.00',
                'or_number' => '87027',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 24,
                'status_id' => 7,
                'tsr_id' => 81,
                'paid_at' => '2024-08-19 09:05:27',
            ),
            79 => 
            array (
                'id' => 82,
                'total' => '8400.00',
                'subtotal' => '8400.00',
                'discount' => '0.00',
                'or_number' => '87028',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 25,
                'status_id' => 7,
                'tsr_id' => 82,
                'paid_at' => '2024-08-19 15:57:49',
            ),
            80 => 
            array (
                'id' => 83,
                'total' => '0.00',
                'subtotal' => '40250.00',
                'discount' => '40250.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 1,
                'has_deduction' => 0,
                'discount_id' => 6,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 8,
                'tsr_id' => 83,
                'paid_at' => '2024-08-19 14:47:38',
            ),
            81 => 
            array (
                'id' => 84,
                'total' => '500.00',
                'subtotal' => '500.00',
                'discount' => '0.00',
                'or_number' => '87030',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 24,
                'status_id' => 7,
                'tsr_id' => 84,
                'paid_at' => '2024-08-19 16:25:44',
            ),
            82 => 
            array (
                'id' => 85,
                'total' => '10850.00',
                'subtotal' => '10850.00',
                'discount' => '0.00',
                'or_number' => '87031',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 25,
                'status_id' => 7,
                'tsr_id' => 85,
                'paid_at' => '2024-08-19 16:25:58',
            ),
            83 => 
            array (
                'id' => 86,
                'total' => '550.00',
                'subtotal' => '550.00',
                'discount' => '0.00',
                'or_number' => '87032',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 25,
                'status_id' => 7,
                'tsr_id' => 86,
                'paid_at' => '2024-08-19 16:26:04',
            ),
            84 => 
            array (
                'id' => 87,
                'total' => '550.00',
                'subtotal' => '550.00',
                'discount' => '0.00',
                'or_number' => '87033',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 25,
                'status_id' => 7,
                'tsr_id' => 87,
                'paid_at' => '2024-08-19 16:26:09',
            ),
            85 => 
            array (
                'id' => 88,
                'total' => '900.00',
                'subtotal' => '900.00',
                'discount' => '0.00',
                'or_number' => '87034',
                'is_paid' => 1,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => 17,
                'collection_id' => 24,
                'status_id' => 7,
                'tsr_id' => 88,
                'paid_at' => '2024-08-19 16:26:14',
            ),
            86 => 
            array (
                'id' => 89,
                'total' => '1550.00',
                'subtotal' => '1550.00',
                'discount' => '0.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 6,
                'tsr_id' => 89,
                'paid_at' => NULL,
            ),
            87 => 
            array (
                'id' => 90,
                'total' => '2000.00',
                'subtotal' => '2000.00',
                'discount' => '0.00',
                'or_number' => NULL,
                'is_paid' => 0,
                'is_free' => 0,
                'has_deduction' => 0,
                'discount_id' => 1,
                'payment_id' => NULL,
                'collection_id' => NULL,
                'status_id' => 6,
                'tsr_id' => 90,
                'paid_at' => NULL,
            ),
        ));

        
    }
}